name: Main - build image and push
# This workflow builds and pushes a Docker image to GitHub Container Registry
# and optionally to Docker Hub.
# It runs nightly at 2 AM UTC and can also be triggered manually.
# The image is tagged with "nightly" and the repository owner is converted to lowercase.
# The workflow uses the GITHUB_TOKEN secret for authentication with GitHub Container Registry.
# Uncomment the Docker Hub section if you want to push to Docker Hub as well.
# The Docker Hub credentials should be stored in the repository secrets as DOCKER_USERNAME and DOCKER_PASSWORD.
# The workflow is triggered on a schedule and can also be run manually.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # allows manual triggering of the workflow

env:
  VERSION_PREFIX: snapshot-v0.0.

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version string
        run: echo "VERSION=${{ env.VERSION_PREFIX }}${{ github.run_number }}" >> $GITHUB_ENV

      - name: Convert repository owner to lowercase
        run: echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build image
        run: docker build -t ghcr.io/${{ env.owner }}/eos_connect:snapshot .

      # Only run tagging and pushing tasks for "push" events
      - name: Tag image with snapshot version
        if: github.event_name == 'push'
        run: docker tag ghcr.io/${{ env.owner }}/eos_connect:snapshot ghcr.io/${{ env.owner }}/eos_connect:${{ env.VERSION }}

      - name: Tag image with latest
        if: github.event_name == 'push'
        run: docker tag ghcr.io/${{ env.owner }}/eos_connect:snapshot ghcr.io/${{ env.owner }}/eos_connect:latest

      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image to GitHub Container Registry
        if: github.event_name == 'push'
        run: |
          docker push ghcr.io/${{ env.owner }}/eos_connect:snapshot
          docker push ghcr.io/${{ env.owner }}/eos_connect:${{ env.VERSION }}
          docker push ghcr.io/${{ env.owner }}/eos_connect:latest

#      - name: Log in to Docker Hub
#        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#      - name: Push image to Docker Hub
#        run: docker push ${{ secrets.DOCKER_USERNAME }}/eos_connect:nightly

  cleanup_old_snapshots:
      needs: publish_image
      runs-on: ubuntu-latest
      steps:
        - name: Delete old snapshot versions
          env:
            GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            # Fetch all versions of the container
            versions=$(curl -s -H "Authorization: Bearer $GHCR_TOKEN" \
              https://ghcr.io/v2/${{ github.repository_owner }}/eos_connect/tags/list | jq -r '.tags[] | select(startswith(\"${VERSION_PREFIX}\"))" | sort -r)

            # Keep the latest 3 versions
            keep=$(echo "$versions" | head -n 3)

            # Delete older versions
            for version in $(echo "$versions" | tail -n +4); do
              echo "Deleting version: $version"
              curl -X DELETE -H "Authorization: Bearer $GHCR_TOKEN" \
                https://ghcr.io/v2/${{ github.repository_owner }}/eos_connect/manifests/$version
            done